# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

from typing import List, Optional
from shiny import App, Inputs, Outputs, Session, reactive, render, ui, module

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:


    return None


_static_assets = ["pond_files","pond_files/libs/quarto-html/tippy.css","pond_files/libs/quarto-html/quarto-syntax-highlighting.css","pond_files/libs/bootstrap/bootstrap-icons.css","pond_files/libs/bootstrap/bootstrap.min.css","pond_files/libs/quarto-dashboard/datatables.min.css","pond_files/libs/clipboard/clipboard.min.js","pond_files/libs/quarto-html/quarto.js","pond_files/libs/quarto-html/popper.min.js","pond_files/libs/quarto-html/tippy.umd.min.js","pond_files/libs/quarto-html/anchor.min.js","pond_files/libs/bootstrap/bootstrap.min.js","pond_files/libs/quarto-dashboard/quarto-dashboard.js","pond_files/libs/quarto-dashboard/stickythead.js","pond_files/libs/quarto-dashboard/datatables.min.js","pond_files/libs/quarto-dashboard/pdfmake.min.js","pond_files/libs/quarto-dashboard/vfs_fonts.js","pond_files/libs/quarto-dashboard/web-components.js","pond_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "pond.html",
    server,
    static_assets=_static_assets,
)
